---
- name: Prepare GUID ENV Variable Across All Hosts
  hosts: all
  tasks:
    - name: Setup GUID as ENV variable on all hosts
      shell: export GUID=`hostname | cut -d"." -f2`; echo "export GUID=$GUID" >> $HOME/.bashrc
    - name: Validate the existence and value of GUID on all hosts
      shell: echo GUID=$GUID

- name: Verify NFS Shared Volumes on Hosts
  hosts: nfs
  tasks:
    - name: NFS Exports
      shell: exportfs

- name: Install Packages and Configure Authentication
  hosts: localhost
  tasks:
    - name: Check required packages are present
      yum:
        name:
          - wget
          - git
          - net-tools
          - bind-utils
          - yum-utils
          - iptables-services
          - bridge-utils
          - bash-completion
          - kexec-tools
          - sos
          - psacct
          - docker-1.13.1
          - atomic-openshift-utils
        enablerepo: rhel-7-server-rpms,rhel-7-server-extras-rpms,rhel-7-server-ose-3.9-rpms,rhel-7-fast-datapath-rpms,rhel-7-server-ansible-2.4-rpms
        state: present

- name: Verify Installation and Configuration of Docker
  hosts: nodes
  tasks:
    - name: Validate supported docker version
      shell: docker version | grep Version | grep 1.13.1
    - name: Enable docker service to run on boot
      shell: systemctl reenable docker
    - name: Restart docker service
      shell: systemctl restart docker
    - name: Validate that the docker service is in running state
      shell: systemctl status docker | grep Active

# - name: Generate Inventory Hosts File
#   hosts: localhost
#   tasks:
#     - name: Generate Inventory script
#       script: /root/ocp_advanced_deployment_homework/scripts/generate_inventory.sh

# - name: Execute the openshift-ansible prerequisites
#   import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml

# - name: Execute the openshift-ansible Deployer
#   import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml

# - name: Verify OpenShift Cluster
#   hosts: masters[0]
#   tasks:
#     - name: copy the .kube directory from master1 to your bastion
#       src: /root/.kube/config
#       dest: /root/.kube/config
#       flat: yes

# - name: Post installation configuration
#   hosts: localhost
#   tasks:
#     - name: make sure you are system:dmin
#       shell: oc whoami | grep system:admin

# - name: Create PVs for Users
#   hosts: nfs
#   tasks:
#     - name:
#       script: scripts/create_pvs.sh
#     - name: Restarting NFS Server...
#       shell: systemctl restart nfs-server

# - name: Create 25 definitions files for PVs 5G size
#   hosts: localhost

# - name: Create 25 definitions files for PVs 10G size

# - name: Create all PVs from definitions files

# - name: Fix NFS Persistent Volume Recycling

# - name: Smoke Test

# - name: Jenkins Setup
#   hosts: localhost
#   tasks:
#     - name: jenkins setup
#       script: ???

# - name: HPA configuration on production deployment of openshift-tasks
#   hosts: localhost
#   tasks:

# - name: Creation of users for Alpha and Beta clients

# - name: Assigning labels to the users according to its group

# - name: Setup the environment for Alpha and Beta clients


#   ....
